# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, performs a Codacy security scan
# and integrates the results with the
# GitHub Advanced Security code scanning feature. For more information on
# the Codacy security scan action usage and parameters, see
# https://github.com/codacy/codacy-analysis-cli-action#usage
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-analysis-cli.

name: Codacy Security Scan

on:
  push:
    branches: [ "main", "feat/startup-quality-infra" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 2 * * 4'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup pnpm (去除 version 字段，避免与 package.json 冲突)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      # Setup Node.js 环境（如有需要，可指定 node-version）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 可选：运行 Lint 或格式化
      - name: Run lint and format
        run: pnpm lint:fix && pnpm format:write

      # 执行 Codacy Analysis CLI 并生成 SARIF 报告
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          output: results.sarif
          output-format: sarif
          fail-on: severity
          gh-code-scanning-compat: true
          # 你可在此添加更多 CLI 配置项

      # 上传 SARIF 文件到 GitHub 安全性
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
