name: Preview (PR -> Vercel)
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - run: npm i -g vercel@latest
      - name: Pull Env
        run: vercel pull --yes --environment=preview --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Build
        run: vercel build --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy
        id: deploy
        run: |
          URL=$(vercel deploy --prebuilt --token $VERCEL_TOKEN)
          echo "url=$URL" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Comment
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.deploy.outputs.url }}'
            const body = `✅ Preview 部署完成: ${url}`
            const {context, github} = require('@actions/github')
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            })
