# .github/workflows/push-exit-check.yml
# 在 push 之前添加 pull --rebase 步骤

name: 自动推送 exit-check.mjs

on:
  push:
    branches:
      - main

jobs:
  push-exit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update exit-check.mjs
        run: echo '// updated by CI' > exit-check.mjs

      - name: Stage changes
        run: git add exit-check.mjs

      - name: Commit changes
        run: git commit -m "ci: update exit-check.mjs" || echo "No changes to commit"

      - name: Pull latest changes before push
        run: git pull origin feat/startup-quality-infra --rebase

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD:feat/startup-quality-infra
