name: Renovate Trigger

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Renovate Bot
        uses: renovatebot/github-action@v43.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
